### ISSUE TITLE
Feat: Add Prettier to the project

### ISSUE THREAD

**Issue by Cor4zon** [chingu-voyages/v46-tier3-team-28#28]
**__Task Description__**
We need to use a code formatter for better code formatting. You can learn how to set it up [here](https://cathalmacdonnacha.com/setting-up-eslint-prettier-in-vitejs) 

**__Technical Considerations__**
You can get more information about that [here](https://prettier.io/docs/en/)

**__Additional Considerations__**
If you have additional questions, feel free to ask me (@Cor4zon).

**Comment by julichow** [comment]
Review Prettier setup
