### ISSUE TITLE
Feat: Add Eslint to the project

### ISSUE THREAD

**Issue by Cor4zon** [chingu-voyages/v46-tier3-team-28#29]
**__Task Description__**
We need to use a linter for our project. ESLint is an industry standard for this. You can learn how to set it up [here](https://cathalmacdonnacha.com/setting-up-eslint-prettier-in-vitejs) 

**__Technical Considerations__**
You can get more information about that [here](https://eslint.org/docs/latest/use/getting-started)

**__Additional Considerations__**
If you have additional questions, feel free to ask me (@Cor4zon).

**Comment by julichow** [comment]
Review Eslint setup
